### ISSUE TITLE
Add PT-PT translation

### ISSUE THREAD

**Issue by viruxe** [BigETI/SAMPLauncherNET#10]
I'll be translating this to TRUE Portuguese in maybe a day or two.

**Comment by BigETI** [comment]
Yea, just leave a pull request for me to review and merge.

**Comment by viruxe** [comment]
@BigETI why is the Designer file replicated for every language?

**Comment by BigETI** [comment]
Designer files are auto generated, and shouldn't be modified by anyone except the IDE.
