### ISSUE TITLE
Clickable weburl

### ISSUE THREAD

**Issue by ziggi** [BigETI/SAMPLauncherNET#14]
Please add something like clickable weburl from the original SA-MP launcher.
![image](https://user-images.githubusercontent.com/1020099/28035611-f08f81d8-65bd-11e7-93c2-0370b136f64c.png)

**Comment by BigETI** [comment]
Should it be visible at the extended server information window, or at the context menu of the server selection?

**Comment by ziggi** [comment]
I think that add ability for going by url with double click is enough. No need to add additional line like in original launcher.

**Comment by BigETI** [comment]
This will be available in the next build.
