### ISSUE TITLE
Different grid view colors

### ISSUE THREAD

**Issue by BigETI** [BigETI/SAMPLauncherNET#17]
According to some people the blue toned colors inside the grid views are not appealing to the eye.

Can someone suggest me some appropriate colors?

**Comment by myudev** [comment]
[5:11 PM] Marcel: Grayisg
[5:11 PM] Marcel: Grayish

**Comment by Hual** [comment]
Marcel - Today at 6:11 PM
Grayisg
Grayish

**Comment by BigETI** [comment]
What about a heavily desaturated blue tone?

**Comment by BigETI** [comment]
This image shows how it would look (see servers grid view), if gray is used.
![grey](https://user-images.githubusercontent.com/4518424/30754734-2c276c3e-9fc4-11e7-861d-44e01bbbc068.png)

**Comment by BigETI** [comment]
This is a desaturated version:
![desaturated-blue](https://user-images.githubusercontent.com/4518424/30772242-f2bd236e-a057-11e7-897a-43c6880e3304.png)

**Comment by BigETI** [comment]
This is the current style of this launcher:
![new-colors](https://user-images.githubusercontent.com/4518424/30783293-bdcd7fa2-a140-11e7-98c8-1f6934c84863.png)

I'll keep this "issue" open for further discussions.

**Comment by myudev** [comment]
Sexy

**Comment by AmirSavand** [comment]
I like this one https://github.com/BigETI/SAMPLauncherNET/issues/17#issuecomment-331711722

**Comment by AmirSavand** [comment]
The other ones don't work at all, they look like windows XP.
