### ISSUE TITLE
sort by number of players get wrong

### ISSUE THREAD

**Issue by Dayvison** [BigETI/SAMPLauncherNET#25]
![image](https://user-images.githubusercontent.com/10089094/31035715-60ebfc3e-a53f-11e7-9d51-ca9b50541d06.png)

**Comment by BigETI** [comment]
![fixed-player-count-order](https://user-images.githubusercontent.com/4518424/31049313-1e1f38ba-a631-11e7-969d-a9eab69bfdb6.png)
This will be fixed in the next version. Thank you.
