### ISSUE TITLE
slow on loading gallery images

### ISSUE THREAD

**Issue by Jlalt** [BigETI/SAMPLauncherNET#27]
Hello, I've recently tried to try this app out and I've realized your application takes 16 seconds to load 416 image. 

is there a way to speed this up?

**Comment by BigETI** [comment]
Right now it reloads all images when the "Gallery" tab is selected. I could implement a caching mechanism to speed up the loading time.

**Comment by BigETI** [comment]
I may have to add a multi-threaded solution to load images without locking the launcher's process.

**Comment by BigETI** [comment]
This has been resolved in the next update, thank you.
