### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by earltacs** [BigETI/SAMPLauncherNET#33]
Are you going to update this too 0.3.DL?

Just asking though...

**Comment by BigETI** [comment]
Yes.

**Comment by BigETI** [comment]
A launcher version will be pushed soon, so there will be no need to update the launcher everytime a new version SA:MP appears. https://github.com/BigETI/SAMPLauncherNET/commit/22154f14d5cc9a839def4739fd04c87117b2728b
