### ISSUE TITLE
Direct users to Wiki page for easier installation

### ISSUE THREAD

**Issue by Southclaws** [BigETI/SAMPLauncherNET#37]
https://github.com/BigETI/SAMPLauncherNET/blob/22154f14d5cc9a839def4739fd04c87117b2728b/SAMPLauncherNET/SAMP.cs#L500

This page will tell people how to get sampctl installed, the releases page is really just an exe dump and is only really useful to power-users who know how to manually install cli tools: `https://github.com/Southclaws/sampctl/wiki/Windows`

**Comment by BigETI** [comment]
This message was implemented, before the sampctl update mechanism was implemented seen at https://github.com/BigETI/SAMPLauncherNET/blob/8a7074022bd31a50e4e9a2a63593de89d6320260/SAMPLauncherNET/MainForm.cs#L1873 and https://github.com/BigETI/SAMPLauncherNET/blob/8a7074022bd31a50e4e9a2a63593de89d6320260/SAMPLauncherNET/SAMPCTLProvider.cs#L54

I can surely modify the message to point to the wiki, if the sampctl update was successful, but the sampctl.exe file is missing somehow.

**Comment by BigETI** [comment]
https://github.com/BigETI/SAMPLauncherNET/commit/24c09b23cad1892e654a1dc2725b9f4dccf40538
