### ISSUE TITLE
Should the launcher provide an ASI plugin loader integration?

### ISSUE THREAD

**Issue by BigETI** [BigETI/SAMPLauncherNET#38]
Since https://github.com/Hual/samp-discord-plugin has been integrated into the launcher, I thought to add support for loading any ASI plugin into the game. There are many good extensions for GTA San Andreas and San Andreas Multiplayer that are pretty useful. However my concern is that many people are going to use this integration to cheat in multiplayer, which is a big no-no in my opinion. My question is should it be a thing for this launcher or not?

**Comment by Southclaws** [comment]
I think this would be a really useful tool. Cheaters are going to cheat, regardless of how easy it is.

Something like this could even make client-side plugins for servers more common so servers can write their own unique features.

Of course there are security concerns so I think the user should be told that third party binaries are very unsafe and an element of trust is required.

**Comment by BigETI** [comment]
I've decided that this will be a thing in the next build.

**Comment by BigETI** [comment]
https://github.com/BigETI/SAMPLauncherNET/commit/6708f5b2dc63900ac67eed6f6d6b7ae1426edacb
