### ISSUE TITLE
Close when launched always active

### ISSUE THREAD

**Issue by Southclaws** [BigETI/SAMPLauncherNET#43]
I can't seem to disable this, every time I launch the default is ticked and I want to keep the browser open.

Repro: untick, close, relaunch

![2018-04-05_10-46-03](https://user-images.githubusercontent.com/1636971/38358904-8f2b498e-38be-11e8-9eb5-965888341f27.gif)

The state of this checkbox should be persisted across sessions somehow.

**Comment by BigETI** [comment]
This should be done in the next build, thank you!

**Comment by BigETI** [comment]
https://github.com/BigETI/SAMPLauncherNET/commit/6708f5b2dc63900ac67eed6f6d6b7ae1426edacb
