### ISSUE TITLE
Enter key to join server

### ISSUE THREAD

**Issue by Southclaws** [BigETI/SAMPLauncherNET#51]
I join and quit my dev server a lot, now that the username dialog box has gone it would be great to just hit enter to join the selected server in the list.

**Comment by BigETI** [comment]
I was about to push some changes to the UI, but Visual Studio decided to trash my project by removing data table columns and constantly spitting errors generated inside the designer.

**Comment by BigETI** [comment]
https://github.com/BigETI/SAMPLauncherNET/commit/e7ffbc2352a18d7b114f4d43c2d5beda21207827
