### ISSUE TITLE
instability and crashes

### ISSUE THREAD

**Issue by RodrigoDornelles** [BigETI/SAMPLauncherNET#53]
I am not able to use the launcher, I downloaded the latest version, it still updates, it arrives at the end it crashes (even running with adm) I only managed to open successfully once (with websocket error), but when I changed the language, it was refresh again and crashed. then can not open again

> MY  PC:
Windows 10 (64 bit)
I5 3.2Ghz
16Gb Ram
GTX 660

**Comment by BigETI** [comment]
Can you please show the error messages including stack trace related to this issue?

**Comment by RodrigoDornelles** [comment]
I can not, only once can see this error, the launcher of failure: (program stopped responding) without crash screen

**Comment by markski1** [comment]
I have had this issue when running the launcher in my Downloads folder.

I moved it to a folder in my C: drive and it began working inmediatly.

**Comment by BigETI** [comment]
SAMPLauncherNET will create files and directories in its working directory. It is best to create a workspace with read and write permissions for this application.

**Comment by BigETI** [comment]
There have been many occurrences that the updater seems to hang. This is known for many months now and the reason for that is that it surely creates a backup after downloading the new binaries. The backup routine runs at the same thread the UI is running. Running CSL aka. SAMPLauncherNET for example inside the downloads directory or the game directory means that it will back up gigabytes of files, which takes a lot of time to do. Also it has been criticized that auto updating procedure should not really be a thing. I might throw out the updater part and put in a dialog to ask the user to update themselves (which can be turned off at the settings), by just opening a browser to download to update manually. What are your opinions about that?

**Comment by markski1** [comment]
Why does it backup it's entire directory as opposed to just itself?

**Comment by Bios-Marcel** [comment]
Updating should be a system thing. Look at chocolatey(nuget?) or scoop. Don't use the working directory, that just sucks. What does the backup routine update and why is it so much. My launcher is less than 200MB including the JRE, how is your backup size so damn high?

**Comment by BigETI** [comment]
> Why does it backup it's entire directory as opposed to just itself?

In case something breaks and files get messed up, this is a way to recover them.

> Don't use the working directory, that just sucks.

Why?

>What does the backup routine back up and why is it so much. My launcher is less than 200MB including the JRE, how is your backup size so damn high?

The launcher itself is small. The backup routine is supposed to update files that might be related to CSL aka. SAMPLauncherNET, which can be the entire directory it has been started from.

**Comment by Bios-Marcel** [comment]
Okay thats super dumb ... just use %APPDATA%/xxx/.

**Comment by BigETI** [comment]
The initial idea was that CSL aka. SAMPLauncherNET should be portable and not installable.

**Comment by markski1** [comment]
In that case why not distribute it as a portable zip moving onwards?

**Comment by BigETI** [comment]
Yeah, but that is literally the same as a self extracting executable (which is what it is right now). The only thing left right now would be to remove the updater executable. I could provide multiple builds including a self extracting executable and a zip or gzip file variant. Back then before I used ILMerge I released build archives instead.

**Comment by BigETI** [comment]
https://github.com/BigETI/SAMPLauncherNET/releases/tag/1.0.7.0

https://github.com/BigETI/SAMPLauncherNET/commit/758ded85fd22e02d56a14482d81f242cc0e4933d
https://github.com/BigETI/SAMPLauncherNET/commit/480ba16255f5f2e50f4e5cc4e2ac1faa2af39df8
https://github.com/BigETI/SAMPLauncherNET/commit/1d079b6360a4593823715dc2ab633ebdc0fd7653

Please tell me if you still have issues with the new build.
