### ISSUE TITLE
Wrong Version

### ISSUE THREAD

**Issue by gabrielcruel123** [BigETI/SAMPLauncherNET#54]
When I try to download SAMP 0.3.7-R2, it downloads 0.3z-R2 instead.

**Comment by BigETI** [comment]
Hello, this behaviour is not repuroducable at this end. Can you please provide more information how you invoked that issue?

**Comment by gabrielcruel123** [comment]
Okay, so, I was looking at the json files to find out what the problem was, and I found [this file](https://raw.githubusercontent.com/BigETI/SAMPLauncherNET/master/versions.json)

I noticed 0.3.7-R2 isn't correct, for example, when I open the launcher and opt to install 0.3.7-R2, it installs 0.3z-R2 instead.

**Comment by BigETI** [comment]
I don't know how that slipped through. SHould be fixed now in https://github.com/BigETI/SAMPLauncherNET/commit/0f4ff98e79a289d4c049cb0d58357208b35daa68

Thank you!
