### ISSUE TITLE
Does this launcher cache server list?

### ISSUE THREAD

**Issue by AmirSavand** [BigETI/SAMPLauncherNET#55]
I'm planing on using this, just a tiny question.

So does it cache or pulls every time you launch it?

**Comment by BigETI** [comment]
It pulls everytime you launch it. However you can point to a locally stored or hosted server list if you want some sort of caching.

**Comment by AmirSavand** [comment]
Is there going to be a caching feature or won't be added at all?

**Comment by BigETI** [comment]
I don't know if it smart to cache online server lists, because they change all the time, including the servers themselves.
