### ISSUE TITLE
Not properly refreshing favorites

### ISSUE THREAD

**Issue by markski1** [BigETI/SAMPLauncherNET#58]
Not sure if related to the latest update, but this started happening this morning. Only instruction to reproduce is to open the client. Sometimes some of the pings are updated but the rest of the information isn't shown until you click on a server.

![2018-12-13_11-11-18](https://user-images.githubusercontent.com/22557859/49943936-e93f8000-fec7-11e8-932c-3834bc9b3fab.gif)

Note this only happens with favorites. Online listings work fine (except for southclaws and official which do not load at all)

**Comment by markski1** [comment]
Happens consistently when opening the client. Will try again later to see if it keeps happening.

**Comment by BigETI** [comment]
Tell me if https://github.com/BigETI/SAMPLauncherNET/commit/33e8e8fa216e2833d0f394891f3dd999241a94b5 fixes the mentioned issues.

**Comment by markski1** [comment]
![imagen](https://user-images.githubusercontent.com/22557859/49962498-2ae62000-fef4-11e8-9bbb-9d8469ce68bf.png)
Looks fixed-ish, sometimes it doesn't query some information but the name is always there, which is good enough.

**Comment by BigETI** [comment]
I might change some things again and I will come back when they are done. Thank you!

**Comment by BigETI** [comment]
Please tell me if https://github.com/BigETI/SAMPLauncherNET/commit/a98b982c0c0cb421f744cee8f9042b0fc893ae8c solves the mentioned issues properly.

**Comment by markski1** [comment]
The issues were resolved. It has also greatly reduced the CPU usage.
