### ISSUE TITLE
Servers get duplicated

### ISSUE THREAD

**Issue by viruxe** [BigETI/SAMPLauncherNET#6]
![image](https://user-images.githubusercontent.com/1616657/27988931-0b8a383c-6426-11e7-81f4-28a0b828454c.png)
And the entries get switched around if you keep clicking on them.
On startup they load fine.

**Comment by BigETI** [comment]
I can't reproduce this behaviour. Can you please tell me exactly how you accomplished this?

And I would like to see your USERDATA.DAT file.

**Comment by MichaelBelgium** [comment]
The second one has other ip so it's not a duplicate, and the first and third have probably other ports? It's coming from your favorite list from the default samp client where it's already impossible to add same ip's :thinking:

**Comment by viruxe** [comment]
Haven't been able to reproduce. On the original client the list is fine. Also notice that it's sorted for the ping tab. The lostcity server's port is 7575.

**Comment by BigETI** [comment]
I could reproduce that. However server entries are not cloned. The sorting mechanism messes with the current selection and update mechanism, where the appearance of the server entries look duplicated.
