### ISSUE TITLE
Nickname problem

### ISSUE THREAD

**Issue by JaggerJam69** [BigETI/SAMPLauncherNET#63]
![image](https://user-images.githubusercontent.com/52425656/64925838-01e61900-d7ff-11e9-955d-eda758fc688e.png)
I'm writing it without spaces, idk why this is coming out.
Also and this 
![image](https://user-images.githubusercontent.com/52425656/64925866-407bd380-d7ff-11e9-8ed7-b8635142e5fb.png)

**Comment by BigETI** [comment]
This problem is not related to this launcher.

This problem seems to be similar to [this issue](https://github.com/BigETI/SAMPLauncherNET/issues/48) posted at https://github.com/BigETI/SAMPLauncherNET/issues/48

**Comment by BigETI** [comment]
I'll close this issue for now.
