### ISSUE TITLE
Clear query when changing filter types

### ISSUE THREAD

**Issue by viruxe** [BigETI/SAMPLauncherNET#9]
Or add the option to clear it.

**Comment by BigETI** [comment]
Is this more practical in your opinion to clear the text field after the filter type changed or keep it as it was before, so the user doesn't have to retype their query?

**Comment by viruxe** [comment]
Maybe just have the option to clear it. Even though I don't see many cases were you would have the need to query the same thing on different filters.

**Comment by BigETI** [comment]
Maybe I could type in a mode name and forget to set the filter type to `mode` before typing.

**Comment by viruxe** [comment]
That seems valid. Then just the clear option it is I guess.

**Comment by BigETI** [comment]
To be honest I don't know if it should be at thing, since the filter system isn't complex at all.
